name: Run dbt Build and Publish Docs on PR Merge to Main

on:
  push:
    branches:
      - main

jobs:
  dbt-prod-build-and-publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Google Cloud Credentials
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | base64 --decode > lumley-analytics-9aabdf12ee21.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/lumley-analytics-9aabdf12ee21.json

      - name: Install dbt and dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install dbt-core dbt-bigquery  # Add other adapters as needed

      - name: Install dbt Packages
        run: |
          source env/bin/activate
          dbt deps  # Install dependencies from packages.yml

      - name: Run dbt Build and Generate Docs
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/lumley-analytics-9aabdf12ee21.json
        run: |
          source env/bin/activate
          dbt build --target prod  # Run models with the prod target
          dbt docs generate  # Generate documentation after the build

      - name: Publish to gh-pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd target
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update dbt docs"
          # Push to the gh-pages branch using the GH_PAT token
          git remote add origin "https://${{ secrets.GH_PAT }}@github.com/lumleyanalytics/lumley_analytics.git"
          git push --force origin master:gh-pages
