name: Publish dbt Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  generate-and-publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt and dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install dbt-core dbt-bigquery  # Add any other necessary dbt adapters

      - name: Set up Google Cloud Credentials
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | base64 --decode > lumley-analytics-9aabdf12ee21.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/lumley-analytics-9aabdf12ee21.json

      - name: Install dbt Packages
        run: |
          source env/bin/activate
          dbt deps

      - name: Generate dbt Docs
        run: |
          source env/bin/activate
          dbt docs generate

      - name: Publish to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Initialize a new repo in the target folder and push to gh-pages
          cd target
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update dbt docs"
          git branch -M gh-pages
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
