name: Run dbt Build on PR Merge to Main

on:
  push:
    branches:
      - main

jobs:
  dbt-prod-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust as necessary

      - name: Set up Google Cloud Credentials
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | base64 --decode > lumley-analytics-sa.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/lumley-analytics-sa.json

      - name: Install dbt and dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install dbt-core dbt-bigquery  # Add other adapters as needed

      - name: Install dbt Packages
        run: |
          source env/bin/activate
          dbt deps  # Install dependencies from packages.yml

      - name: Run dbt Build (Prod)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/lumley-analytics-sa.json
        run: |
          source env/bin/activate
          dbt build --target prod  # Run models with the prod target
