name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Google Cloud Authentication
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | base64 -d > /tmp/gha-creds.json
          gcloud auth activate-service-account --key-file=/tmp/gha-creds.json
          gcloud config set project lumley-analytics

      - name: Verify Authentication
        run: |
          gcloud auth list
          gcloud config list

      - name: Debug Artifact Registry Permissions
        run: |
          gcloud artifact-registry repositories list --location=us-east4

      - name: Reconfigure Docker Auth for Artifact Registry
        run: |
          gcloud auth configure-docker us-east4-docker.pkg.dev
          cat ~/.docker/config.json  # Confirm Docker is configured for Artifact Registry

      - name: Test Docker Pull from Artifact Registry (Debugging)
        run: |
          docker pull us-east4-docker.pkg.dev/lumley-analytics/lumley-analytics-dbt/nonexistent-image || echo "Expected error due to nonexistent image"

      - name: Create Service Account Key File for Docker
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | base64 -d > lumley-analytics-9aabdf12ee21.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          PROJECT_ID: "lumley-analytics"
          REPO_NAME: "lumley-analytics-dbt"
        run: |
          docker build -t us-east4-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/lumley-analytics-dbt-snapshot .
          docker push us-east4-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/lumley-analytics-dbt-snapshot
