name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          PROJECT_ID: "lumley-analytics"
        run: |
          docker build -t gcr.io/$PROJECT_ID/lumley-analytics-dbt-snapshot .
          docker push gcr.io/$PROJECT_ID/lumley-analytics-dbt-snapshot

      - name: Deploy Cloud Run Job
        env:
          PROJECT_ID: "lumley-analytics"
          REGION: "us-east4"  # Update with your Cloud Run region
        run: |
          gcloud run jobs update dbt-snapshot-job \
            --image gcr.io/$PROJECT_ID/lumley-analytics-dbt-snapshot \
            --region $REGION
