name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure Docker to Use Artifact Registry
        run: |
          gcloud auth configure-docker us-east4-docker.pkg.dev

      - name: Build and Push Docker Image
        env:
          PROJECT_ID: "lumley-analytics"
          REPO_NAME: "lumley-analytics-dbt"  # Set your Artifact Registry repository name here
        run: |
          docker build -t us-east4-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/lumley-analytics-dbt-snapshot .
          docker push us-east4-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/lumley-analytics-dbt-snapshot

      - name: Deploy Cloud Run Job
        env:
          PROJECT_ID: "lumley-analytics"
          REGION: "us-east4"  # Ensure this matches your Artifact Registry and Cloud Run region
          REPO_NAME: "lumley-analytics-dbt"
        run: |
          gcloud run jobs update lumley-analytics-dbt \
            --image us-east4-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/lumley-analytics-dbt-snapshot \
            --region $REGION
